Home2
valeria-ivasheva/homework-2-semester pull request #2
Opened 2018-02-23 15:58 UTC by valeria-ivasheva

Homework 2

2018-02-24 09:52 UTC, yurii-litvinov requested changes

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +        public StackElement next;
Ой. Паблик-полей быть не должно, нарушение инкапсуляции. Лучше было сделать StackElement вложенным классом в Stack, причём private-классом

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +            next = null;
Ненужная инициализация, поля и так проинициализируются нулями

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +            head = null;
Тут тоже, оно и так null

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +        private int size = 0;
И тут, оно и так 0

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +        }
Лучше `public bool IsEmpty() => size == 0;`

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +            StackElement newElement = new StackElement(value);
Тут лучше `var newElement = new StackElement(value);` --- тип переменной очевиден из присваивания

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +            else
Тут else можно было не писать, ветка then заканчивается return-ом, так что сюда бы управление всё равно не дошло

2018-02-24 09:52 UTC, yurii-litvinov commented on homework2/Stack/Stack/Stack.cs
> +                temp.next = null;
Это можно было не делать, head перестаёт указывать на temp, так что как только мы вернёмся из Pop(), на temp больше вообще никто не будет указывать, так что её сборщик мусора соберёт. И неважно, чему равны его поля.

2018-02-24 14:05 UTC, yurii-litvinov approved these changes
👍

2018-02-24 14:05 UTC, yurii-litvinov commented on homework2/Stack/Stack/Program.cs
> +            Stack stack = new Stack();
Тут лучше var, тип переменной очевиден из присваивания

2018-02-24 19:40 UTC, yurii-litvinov requested changes
В целом всё так, но от списка я бы хотел побольше функциональности, а хеш-таблицу просто надо немного поправить

2018-02-24 19:40 UTC, yurii-litvinov commented on homework2/List/List/List.cs
> +        public bool IsHaveElement(int value)
HasElement благозвучнее

2018-02-24 19:40 UTC, yurii-litvinov commented on homework2/List/List/List.cs
> +    }
Я бы хотел ещё вставку в произвольную позицию, получение значения по позиции и удаление по позиции, а не только по значению.

2018-02-24 19:40 UTC, yurii-litvinov commented on homework2/List/List/List.cs
> +                Console.WriteLine("This element does not exist {0}", value);
Лучше `Console.WriteLine($"This element does not exist {value}");`

2018-02-24 19:40 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/HashTable.cs
> +        List[] buckets = new List[100];
Надо явно указывать модификаторы видимости

2018-02-24 19:40 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/HashTable.cs
> +        }
Не уверен, что это нужно, у Object ведь есть метод GetHashCode

2018-02-24 19:40 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/HashTable.cs
> +            if (buckets[number] == null)
Мм, может отрицательное хеш-значение получиться

2018-02-24 19:40 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/HashTable.cs
> +        public bool IsHaveElement(string value)
HasElement было бы благозвучнее

2018-02-25 18:30 UTC, yurii-litvinov requested changes

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/Program.cs
> +            var stackArray = new StackArray();
Не, хотелось StackCalculator сделать отдельным классом, причём так, чтобы в его коде вообще не упоминались StackArray и Stack, только IStack

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/Program.cs
> +                }
Есть метод string.Split(), который сразу превратит строку в список строк, поделенных по пробелу (или по другому символу или даже по набору символов)

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/Program.cs
> +                    if (temp == "/" && (bArray == 0 || bStack == 0))
Нельзя double сравнивать оператором `==`, они почти никогда не будут равны из-за потерь точности. Надо что-то вроде `Math.Abs(bArray) < 0.00001`.

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/Program.cs
> +        private static double Arithmetic(string symbol, double a, double b)
Методы должны называться глаголами, например, Calculate, или вот ApplyArithmeticOperator

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/Program.cs
> +            }
Это лучше записать через foreach

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/StackArray.cs
> +            stack[i] = value;
А что будет, если положить больше 100 элементов? :) Проверка на пустой стек есть, а на полный нету

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/HashTable.cs
> +        }
Есть же Math.Abs. Вряд ли никому бы в голову не пришло сделать такую функцию в стандартной библиотеке

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/HashTable.cs
> +        private int abs(int value)
Кстати, методы должны называться с заглавной

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/List.cs
> +        private void FixIndex(ListElement element, int index)
Такая внимательная работа с индексами, но зачем? Кажется, в коде с индексами никто ничего не делает, они только сохраняются и поправляются по необходимости. Их точно нужно хранить?

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/List.cs
> +
Лишняя пустая строчка :)

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/List.cs
> +                head = temp.next;
А если список и так пуст?

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/HashTable/HashTable/List.cs
> +            if (temp.value == value)
А если список пуст? :)

2018-02-25 18:30 UTC, yurii-litvinov commented on homework2/List/List/List.cs
> +﻿using System;
В общем-то, я в хеш-таблице написал комментарии к списку, поэтому давайте хешщ-таблица будет зачтена, а список надо поправить.

2018-02-26 20:40 UTC, valeria-ivasheva commented on homework2/List/List/List.cs
> +    }
Я для этого и ввела индексы

2018-02-27 05:40 UTC, yurii-litvinov requested changes
Самое интересное --- StackCalculator.cs --- не выложили :) И со списком --- не надо ничего добавлять, надо убрать index или объяснить, зачем его хранить в элементе

2018-02-27 05:40 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/Program.cs
> +               var calculatorArray = new StackCalculator(str, new StackArray());
С отступом что-то не так

2018-02-28 17:53 UTC, yurii-litvinov approved these changes
Всё хорошо, все зачтены

2018-02-28 17:53 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/StackCalculator.cs
> +        string str;
Надо писать явные модификаторы видимости

2018-02-28 17:53 UTC, yurii-litvinov commented on homework2/Calculator/Calculator/StackCalculator.cs
> +            for (int i = 0; i < elements.Length; i++)
Поскольку i нигде не используется, это лучше и проще было бы записать через foreach

2018-03-01 20:57 UTC, merged